# inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rubycw

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'gems/**/*'
  NewCops: enable

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Rubycw:
  Enabled: true

Security:
  Enabled: true

# この設定ファイルでは、以下Aのルールを採用しています。
# A .rubocop.ymlシンプルに、ゆるめにやりたいんじゃ
# https://hoshinotsuyoshi.com/post/rubocop_yaml/
