version: "3.7"
# ローカル環境での稼働確認用
services:     
    web:
        # buildはせず、存在するdocker imageを利用するよう指定
        image: yakitori99/trip-weather-backend-rails:v0.1.0
        ports:
            # web server
            - 3000:3000
        # ホストOSの起動時、コンテナの不慮の停止時などにコンテナを自動起動するよう指定
        restart: always
        environment:
            # Herokuと同様の設定でローカルで動かせるよう、環境変数PORTを設定
            PORT: "3000"